import SwiftUI
struct ListDetailView: View {
    let list: GroceryList; @State private var items: [ListItem] = []; @State private var adding = false; @State private var deletingList = false; @State private var editing: ListItem?; @Environment(\.dismiss) private var dismiss
    var body: some View { List { ForEach(items) { item in Button { Task { await toggle(item) } } label: { HStack { Image(systemName: item.isComplete ? "checkmark.circle.fill" : "circle").foregroundStyle(item.isComplete ? .green : .secondary); VStack(alignment: .leading) { Text(item.name).strikethrough(item.isComplete).foregroundStyle(item.isComplete ? .secondary : .primary); if let quantity = item.quantity { Text(quantity).font(.caption).foregroundStyle(.secondary) } }; Spacer(); Circle().fill(item.colorLabel.swiftUIColor).frame(width: 12,height: 12) } }.swipeActions { Button("Delete", role: .destructive) { Task { await delete(item) } }; Button("Edit") { editing = item }.tint(.blue) } } }.navigationTitle(list.name).toolbar { ToolbarItem(placement: .topBarTrailing) { Button { adding = true } label: { Image(systemName: "plus") } }; ToolbarItem(placement: .topBarTrailing) { Menu { Button("Delete List", role: .destructive) { deletingList = true } } label: { Image(systemName: "ellipsis.circle") } } }.task { await load() }.sheet(isPresented: $adding) { ItemEditor(title: "New Item", item: nil) { name,quantity,color in await add(name,quantity,color) }.presentationDetents([.height(255)]).presentationDragIndicator(.visible) }.sheet(item: $editing) { item in ItemEditor(title: "Edit Item", item: item) { name,quantity,color in await update(item,name,quantity,color) }.presentationDetents([.height(255)]).presentationDragIndicator(.visible) }.confirmationDialog("Delete \(list.name)?", isPresented: $deletingList, titleVisibility: .visible) { Button("Delete List", role: .destructive) { Task { try? await APIClient.shared.send("/api/lists/\(list.id)", method: "DELETE"); dismiss() } } } message: { Text("This permanently removes the list and its items from the app.") } }
    private func load() async { struct Response: Decodable { let items: [ListItem] }; items = (try? await APIClient.shared.request("/api/lists/\(list.id)/items"))?.items ?? [] }
    private func toggle(_ item: ListItem) async { let endpoint = item.isComplete ? "uncomplete" : "complete"; try? await APIClient.shared.send("/api/items/\(item.id)/\(endpoint)", method: "POST"); await load() }
    private func delete(_ item: ListItem) async { try? await APIClient.shared.send("/api/items/\(item.id)", method: "DELETE"); items.removeAll { $0.id == item.id } }
    private func add(_ name: String,_ quantity: String,_ color: ItemColor) async { struct Body: Encodable { let name: String; let quantity: String; let colorLabel: ItemColor }; struct Response: Decodable { let item: ListItem }; if let response: Response = try? await APIClient.shared.request("/api/lists/\(list.id)/items", method: "POST", body: Body(name: name,quantity: quantity,colorLabel: color)) { items.append(response.item) } }
    private func update(_ item: ListItem,_ name: String,_ quantity: String,_ color: ItemColor) async { struct Body: Encodable { let name: String; let quantity: String; let colorLabel: ItemColor }; struct Response: Decodable { let item: ListItem }; if let response: Response = try? await APIClient.shared.request("/api/items/\(item.id)", method: "PATCH", body: Body(name:name,quantity:quantity,colorLabel:color)), let i = items.firstIndex(where: { $0.id == item.id }) { items[i] = response.item } }
}
struct ItemEditor: View { let title: String; let item: ListItem?; let save: (String,String,ItemColor) async -> Void; @Environment(\.dismiss) private var dismiss; @FocusState private var nameFocused: Bool; @State private var name: String; @State private var quantity: String; @State private var color: ItemColor
    init(title: String,item: ListItem?,save: @escaping (String,String,ItemColor) async -> Void) { self.title=title; self.item=item; self.save=save; _name=State(initialValue:item?.name ?? ""); _quantity=State(initialValue:item?.quantity ?? ""); _color=State(initialValue:item?.colorLabel ?? .blue) }
    var body: some View { VStack(spacing: 18) { HStack { Text(title).font(.headline); Spacer(); Button { dismiss() } label: { Image(systemName: "xmark.circle.fill").font(.title2).foregroundStyle(.secondary) }.accessibilityLabel("Cancel") }; HStack(spacing: 12) { TextField("Name",text:$name).focused($nameFocused).submitLabel(.done); TextField("Quantity",text:$quantity).multilineTextAlignment(.trailing).frame(maxWidth: 100).textInputAutocapitalization(.never) }.font(.body).padding(14).background(.quaternary, in: RoundedRectangle(cornerRadius: 12)); Picker("Color label",selection:$color) { ForEach(ItemColor.allCases) { c in Circle().fill(c.swiftUIColor).frame(width: 20,height: 20).tag(c).accessibilityLabel(c.rawValue.capitalized) } }.pickerStyle(.segmented); HStack { Button { dismiss() } label: { Image(systemName:"xmark").frame(maxWidth:.infinity) }.buttonStyle(.bordered); Button { Task { await save(name,quantity,color); dismiss() } } label: { Image(systemName:"checkmark").frame(maxWidth:.infinity) }.buttonStyle(.borderedProminent).disabled(name.trimmingCharacters(in:.whitespacesAndNewlines).isEmpty) } }.padding().onAppear { nameFocused = item == nil } } }
extension ItemColor { var swiftUIColor: Color { switch self { case .red: return .red; case .orange: return .orange; case .yellow: return .yellow; case .green: return .green; case .mint: return .mint; case .blue: return .blue; case .purple: return .purple; case .pink: return .pink } } }
